### Testando se a aplicação está rodando
GET http://localhost:5000

### Listando os usuários
GET http://localhost:5000/api/users/list

### Listando as tarefas
GET http://localhost:5000/api/tasks/list

### Criando um usuário
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas@gmail.com",
    "password": "12345"
}

### Criando uma tarefa
POST http://localhost:5000/api/tasks/create
Content-Type: application/json

{
    "title": "Comprar Tomate",
    "description": "Ir no Condor comprar tomate",
    "dueDate": "2024-10-20",
    "userId": 1
}

### Deletando um usuário
DELETE http://localhost:5000/api/users/delete/1

### Deletando uma tarefa
DELETE http://localhost:5000/api/tasks/delete/1