@base_url = http://localhost:5000/api

### Testando se a aplicação está rodando
GET http://localhost:5000/




##########################
####### USUÁRIOS #########
##########################

### Listando os usuários
GET {{base_url}}/users/list

### Criando um usuário
POST {{base_url}}/users/register
Content-Type: application/json

{
    "name": "Tiago",
    "email": "tiago@gmail.com",
    "password": "12345"
}

### Atualiza um usuário
PUT {{base_url}}/users/update/1
Content-Type: application/json

{
    "name": "Thiago Tinfre Marcelino",
    "email": "thiagotinfre@hotmail.com",
    "password": "54321"
}

### Deletando um usuário
DELETE {{base_url}}/users/delete/1






##########################
####### TAREFAS ##########
##########################

### Listando as tarefas
GET {{base_url}}/tasks/list

### Criando uma tarefa
POST {{base_url}}/tasks/create
Content-Type: application/json

{
    "title": "Criar endpoints",
    "description": "Utilizar material de aula",
    "dueDate": "2024-11-20",
    "user": {
        "id": 1
    },
    "tag": {
        "id": 2
    },
    "project": {
        "id": 2
    }
}

### Atualiza uma Task
PUT {{base_url}}/tasks/update/1
Content-Type: application/json

{
    "title": "Tarefa atualizada 6",
    "description": "Descrição atualizada",
    "dueDate": "2024-10-30",
    "status": "Em andamento",
    "user": {
        "id": 1
    },
    "tag": {
        "id": 2
    },
    "project": {
        "id": 2
    }
}

### Deletando uma tarefa
DELETE {{base_url}}/tasks/delete/1





##########################
######### TAGS ###########
##########################

### Lista todas as Tags
GET {{base_url}}/tags/list

### Cria Tag 
POST {{base_url}}/tags/create
Content-Type: application/json

{
    "name": "Trabalho",
    "color": "#FFA500",
    "priority": "Alta"
}

### Atualiza uma Tag 
PUT {{base_url}}/tags/update/1
Content-Type: application/json

{
    "name": "Tag Atualizada",
    "color": "#FF0000",
    "priority": "Média"
}

### Deleta uma Tag 
DELETE {{base_url}}/tags/delete/1





##########################
####### PROJETOS #########
##########################

### Lista todos os projetos
GET {{base_url}}/projects/list

### Cria um projeto
POST {{base_url}}/projects/create
Content-Type: application/json

{
    "name": "Desenvolvimento Web",
    "description": "Professor Diogo",
    "startDate": "2024-10-20",
    "finalDate": "2024-11-20"
}

### Atualiza um Projeto 
PUT {{base_url}}/projects/update/1
Content-Type: application/json

{
    "name": "Projeto Atualizado",
    "description": "Descrição atualizada",
    "startDate": "2024-10-30",
    "finalDate": "2024-11-50"
}

### Deleta um Projeto
DELETE {{base_url}}/projects/delete/1