### Testando se a aplicação está rodando
GET http://localhost:5000

### Listando os usuários
GET http://localhost:5000/api/users/list

### Listando as tarefas
GET http://localhost:5000/api/tasks/list

### Lista todas as Tags
GET http://localhost:5000/api/tags/list

### Lista todos os projetos
GET http://localhost:5000/api/projects/list 



### Criando um usuário
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas@gmail.com",
    "password": "12345"
}

### Criando uma tarefa
POST http://localhost:5000/api/tasks/create
Content-Type: application/json

{
    "title": "Comprar Tomate",
    "description": "Ir no Condor comprar tomate",
    "dueDate": "2024-10-20",
    "userId": 1
}

### Criando Tag 
POST http://localhost:5000/api/tags/create
Content-Type: application/json

{
    "name": "Prioridade",
    "color": "#00FF00",
    "priority": "Alta"
}

### Cria um projeto
POST http://localhost:5000/api/projects/create
Content-Type: application/json

{
    "name": "Agenda pessoal de Outubro",
    "description": "Tarefas do dia a dia",
    "startDate": "2024-10-01",
    "finalDate": "2024-10-31",
    "userId": 1
}




### Deletando um usuário
DELETE http://localhost:5000/api/users/delete/1

### Deletando uma tarefa
DELETE http://localhost:5000/api/tasks/delete/1

### Deletando uma Tag 
DELETE http://localhost:5000/api/tags/delete/1

### Deletando uma Project
DELETE http://localhost:5000/api/projects/delete/1




### Atualiza uma User
PUT http://localhost:5000/api/users/update/1
Content-Type: application/json

{
    "name": "Thiago Tinfre Marcelino",
    "email": "thiagotinfre@hotmail.com",
    "password": "54321"
}

### Atualiza uma Task
PUT http://localhost:5000/api/tasks/update/1
Content-Type: application/json

{
    "title": "Fut sexta",
    "description": "Fut com a galera da firma",
    "dueDate": "2024-10-25",
    "finished": true
}

### Atualiza uma Tag 
PUT http://localhost:5000/api/tags/update/1
Content-Type: application/json

{
    "name": "Prioridade Atualizada",
    "color": "#FF0000",
    "priority": "Média"
}

### Atualiza o Projeto
PUT http://localhost:5000/api/projects/update/1
Content-Type: application/json

{
    "name": "Agenda pessoal de Novembro",
    "description": "Coisas marcadas para o próximo mês",
    "startDate": "2024-11-01",
    "finalDate": "2024-11-30"
}