@base_url = http://localhost:5000/api

### Testando se a aplicação está rodando
GET http://localhost:5000/

### Listando os usuários
GET {{base_url}}/users/list

### Listando as tarefas
GET {{base_url}}/tasks/list

### Lista todas as Tags
GET {{base_url}}/tags/list

### Lista todas as Tags
GET {{base_url}}/projects/list

### Lista todos os projetos
GET {{base_url}}/projects/list

### Criando um usuário
POST {{base_url}}/users/register
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas@gmail.com",
    "password": "12345"
}

### Criando uma tarefa
POST {{base_url}}/tasks/create
Content-Type: application/json

{
    "title": "Comprar Tomate",
    "description": "Ir no Condor comprar tomate",
    "dueDate": "2024-10-20",
    "userId": 1,
    "projectId": 1,
    "tagId": 1
}

### Criando Tag 
POST {{base_url}}/tags/create
Content-Type: application/json

{
    "name": "Prioridade",
    "color": "#00FF00",
    "priority": "Alta"
}

### Criando um projeto
POST {{base_url}}/projects/create
Content-Type: application/json

{
    "name": "Prioridade",
    "description": "#00FF00",
    "startDate": "2024-10-20",
    "finalDate": "2024-11-20"
}

### Deletando um usuário
DELETE {{base_url}}/users/delete/1

### Deletando uma tarefa
DELETE {{base_url}}/tasks/delete/1

### Deletando uma Tag 
DELETE {{base_url}}/tags/delete/1

### Atualiza uma User
PUT {{base_url}}/users/update/1
Content-Type: application/json

{
    "name": "Thiago Tinfre Marcelino",
    "email": "thiagotinfre@hotmail.com",
    "password": "54321"
}

### Atualiza uma Task
PUT {{base_url}}/tasks/update/1
Content-Type: application/json

{
    "title": "Fut sexta",
    "description": "Fut com a galera da firma",
    "dueDate": "2024-10-25",
    "finished": true
}

### Atualiza uma Tag 
PUT {{base_url}}/tags/update/1
Content-Type: application/json

{
    "name": "Prioridade Atualizada",
    "color": "#FF0000",
    "priority": "Média"
}